/* Generated by compiling with gcc 4.4 (or higher?) as follows:
**
** gcc -g -o hello.out hello.c
**
** To run the test that shows the error, do a readelf dump:
** readelf.py --debug-dump=info hello.out
** 
** When using an unmodified descriptions.py, you will get a 
** python exception when it tries to read the 'ijk' element 
** from the elf file. My new version of descriptions.py fixes 
** this problem.
*/

#include <stdio.h>

struct def
{
	int ijk;
	char c;
	long long lint;
	float mno;
	int bit1 : 1;
	int bit3 : 3;
	int bit2 : 2;
	int bit4 : 4;
//};
}__attribute__((__packed__));

const int GLOBAL_CONST;

int tryGlobal;
struct def hiLo;

int main()
{
	int abc;
	printf("Hello World\n");
	return 0;
}

